# ----
# Site

title: Capoeira Camara
url: "https://сapoeiracamara.github.io/"
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Неофициальная библиотека знаний школы Capoeira Camara
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Шаблон в GitHub
  links:
    - https://github.com/capoeiracamara/capoeiracamara.github.io/

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

social_icons:
  - Instagram
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video
  - Song

_comments:
